version: '3'
services:
        web:
                build: .
                environment:
                        - REDIS_HOST=redis
                ports:
                        - "5030:5030"
                depends_on:
                        - redis
        redis:
                image: redis
